language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: gV9NaQl7gpuVz7X2Cr0XT0dpHa0MkiaAaqis6Mz1gFQ/CNy09O7Nwh04vk9Q0o3Brq34ltOKhFVrTWl5KMCInju/QIKAA5jYQRwx3POHB5BOlnjTMgeEF0HW/zaOChI3QmljtgcUBy/K3ZdVEt4/XlspWzhj+wMH/1N9BTZ4peVmwQ34RZd283MrqmrI6KctoBQb4xTsl600x+fJ787/AZnQVgzq3dYf+RWifNQTPxl/peaLjJ9vdQKXPwu7fhO8FhGuopkQpriG1cOQwnHhWinUSSumGY4EAKT7ioZ2VmPKWzid4rPwStHJSrfOMDooLK3PqBHfIlNulOJqbgyC1XmU9ql1srV06NEwQtaAha56aIf0L4XXoLoLu+C0p13HhTDGc0WzAxsAaJ6WQtROfM4ZuBygvHraVnK2kIo3ipAGqVICwOaHY9sluoVRAhm2xwCV4wSQFOOT0McUH5GinRulGNHh+Bbu78G4IyYbx69sKYO0fMUdG2Ck3Zc7U/tr0kLcN4Pl2jILm5pKs6+MmvtFBDPFmU3iCKy0uw+VFcD2CdhRxTpchts9OHiVDY2Rw6ghJNrUFmLorWiGlx5Yt3RO10rZRcLBaFSTF8dAsvnsUPBp4+l2CtdqCbMA8Sv+6Eh9TPOp8ZLojyhSJPI6v4JoLB0ElXAz4DpCxQopdbM=
  app: sleepy-scrubland-19366
  on:
    repo: sulfurshade/blog-app-mongoose-challenge-solution
